### ISSUE TITLE
How to read points3d.bin?

### ISSUE THREAD

**Issue by zjp-shadow** [GAP-LAB-CUHK-SZ/MVImgNet#1]
Thank you for your hard work in making this data set open. 
I have downloaded part of the MVImgNet, and I am curious about how to read `point3d.bin` to get the pointclouds.
Can you give me an example?

**Comment by Larry-u** [comment]
You can refer to the `read_points3d_binary` function in `colmap_read_model.py` from COLMAP to read `point3d.bin`, e.g.
https://github.com/Fyusion/LLFF/blob/master/llff/poses/colmap_read_model.py
