### ISSUE TITLE
Do you have any plan to add textual annotations?

### ISSUE THREAD

**Issue by bluestyle97** [GAP-LAB-CUHK-SZ/MVImgNet#14]
Hi, congratulations on your fantastic work! I believe providing textual descriptions for MVImgNet and MVPNet would facilitate a lot of applications, such as multi-modal pretraining. Do you have any plan to do this?

**Comment by mutianxu** [comment]
Hi,

Thanks for raising this!

We indeed have a plan to add textual annotations, hoping to release it in the future.
