### ISSUE TITLE
Camera poses

### ISSUE THREAD

**Issue by katjaschwarz** [GAP-LAB-CUHK-SZ/MVImgNet#15]
Hi, thank you for the fantastic dataset!
I saw that sometimes there are multiple cameras for a sample (e.g. for mvi_30.zip 175/280142be/sparse/0/cameras.bin and 175/280142be/sparse/1/cameras.bin). They sometimes seem to correspond to the same images - which ones are the correct ones to use and what do the different cameras correspond to?

**Comment by Larry-u** [comment]
We enforce a single camera during COLMAP sparse reconstruction. However, if few images in a video contains less view-consistent features, they will be regarded as shot by another camera, and output a new camera pose, e.g. sparse/1. Usually, we use sparse/0 as the correct one and ignore the others.

**Comment by katjaschwarz** [comment]
Ok, got it! Thank you for the explanation.
