### ISSUE TITLE
About download MVPNET dataset

### ISSUE THREAD

**Issue by Roywangj** [GAP-LAB-CUHK-SZ/MVImgNet#16]
@hugoycj
hi, i cant download the raw MVPNET for the internet due to network stability and speed, do you have other ways for downloading the dataset like google drive or baidu pan?

Besides, would you kindly to explane the difference between the raw dataset and the preprocessed dataset from https://github.com/hugoycj/MVImgNet_3D_Pretraining?

And would you plan to release the training code of PointNet++\PointMLP\PCT ,(as in Tab.12) ，one of them will be enough.

Best wishes,

**Comment by hugoycj** [comment]
Thank you for reaching out with your questions about the MVPNET dataset. I apologize for the difficulties you've had in downloading and using the data. Let me try to address your questions:

Regarding downloading the raw 87GB dataset, I understand your concerns with network speed and stability. Unfortunately I do not have an alternative download location available right now.  I will look into options like Google Drive or Baidu for providing the data, and follow up if I can get a mirror set up. 

Regarding the differences between the raw and preprocessed data, the preprocessed data downsampled the raw point clouds to reduce the number of points, and normalized the point cloud data.

We will integrate the baseline code for MVPNet classification later this week
