### ISSUE TITLE
The error in downloading the dataset

### ISSUE THREAD

**Issue by WhynotHAHA** [GAP-LAB-CUHK-SZ/MVImgNet#17]
Hi, when I try to download a file in the data set, the following error message appears after a period of downloading. How can I fix it?
![image](https://github.com/GAP-LAB-CUHK-SZ/MVImgNet/assets/92723497/89baa222-631f-4c7f-948c-b000e3e1529c)

**Comment by WhynotHAHA** [comment]
![image](https://github.com/GAP-LAB-CUHK-SZ/MVImgNet/assets/92723497/24fa4e1a-1e8a-4257-9663-3f5cf8446a67)

**Comment by jasonyzhang** [comment]
I am also having some issues downloading the dataset. In particular, downloads are easily interrupted. Here's some things that seem to help:

1. Converting the `curl` command to `wget` allows downloads that are interrupted to be resumable (e.g. by using [this](https://curlconverter.com/wget/)). With `wget`, adding a `-c` flag resumes the download so that you don't lose progress
2. Replacing the output name and download name with the corresponding file index makes it possible to write a script to download the files programmatically
3. It seems like the URL/cookie needs to be updated periodically if using a script?

**Comment by kam1107** [comment]
> I am also having some issues downloading the dataset. In particular, downloads are easily interrupted. Here's some things that seem to help:
> 
> 1. Converting the `curl` command to `wget` allows downloads that are interrupted to be resumable (e.g. by using [this](https://curlconverter.com/wget/)). With `wget`, adding a `-c` flag resumes the download so that you don't lose progress
> 2. Replacing the output name and download name with the corresponding file index makes it possible to write a script to download the files programmatically
> 3. It seems like the URL/cookie needs to be updated periodically if using a script?

Hi! I wonder how do you download the dataset from command line? Many thanks!

**Comment by jasonyzhang** [comment]
https://github.com/GAP-LAB-CUHK-SZ/MVImgNet#tips-for-downloading-mvimgnet-through-ubuntu

**Comment by yixchen** [comment]
Attaching a preliminary [script](https://gist.github.com/yixchen/7f9af12a40230f76289988a3181135e3) just in case anyone needs it. Construct the links.txt and headers following the above tips. As Jason also points out, the cookie needs to be updated periodically.

**Comment by ShoufaChen** [comment]
In case it might be helpful, provid a bash script here:

```
for IDX in $(seq -w 00 42);
do
  echo $IDX
  curl "a_long_prefix_path$IDX%2Ezip" \
    -H 'authority: cuhko365-my.sharepoint.com' \
    ......................
    some lines include -H 'authority', cookie, etc
    ......................
    --compressed --output mvi_${IDX}.zip
done
```

note that you should replace `a_long_prefix_path` with the real string you get from https://github.com/GAP-LAB-CUHK-SZ/MVImgNet#tips-for-downloading-mvimgnet-through-ubuntu . It should look like:
```
https://balabala...5FRelease%2Fmvi%5F
```

Fortunatelly, all these 42 zip files share this same prefix, so you just need get it once.

**Comment by Ir1d** [comment]
@ShoufaChen Thanks for sharing. How did you obtain the `https://balabala...5FRelease%2Fmvi%5F` ? On my side, I get a fixed url `https://cuhko365-my.sharepoint.com/personal/gaplab_cuhk_edu_cn/_layouts/15/download.aspx?UniqueId=`

**Comment by ShoufaChen** [comment]
@Ir1d You can get this url prefix from [here](https://docs.google.com/document/d/1krVb4B3rZw-0FaBBPS7c3SJKfqq5AVYTs2HN2LnlBPQ/edit#heading=h.2ukfzxh5c9pq). It should start with `https://cuhko365-my.sharepoint.com/` while end with `mvi%5F00%2Ezip` for `mvi_00.zip`. Then just change the `00` part in `mvi%5F00%2Ezip` with the bash for loop variable `$IDX`.

Remember to change the single quotes  `'` to double quotes `''`.

**Comment by ai1361720220000** [comment]
> In case it might be helpful, provide a bash script here:
> 
> ```
> for IDX in $(seq -w 00 42);
> do
>   echo $IDX
>   curl "a_long_prefix_path$IDX%2Ezip" \
>     -H 'authority: cuhko365-my.sharepoint.com' \
>     ......................
>     some lines include -H 'authority', cookie, etc
>     ......................
>     --compressed --output mvi_${IDX}.zip
> done
> ```
> 
> note that you should replace `a_long_prefix_path` with the real string you get from [here](https://docs.google.com/document/d/1krVb4B3rZw-0FaBBPS7c3SJKfqq5AVYTs2HN2LnlBPQ/edit#heading=h.2ukfzxh5c9pq). It should look like:
> 
> ```
> https://balabala...5FRelease%2Fmvi%5F
> ```
> 
> Fortunatelly, all these 42 zip files share this same prefix, so you just need get it once.
> 
> **Note:** Remember to replace the single quotes `'` to double quotes `"` so that the variable `$IDX` can be expanded.

i used this bash command, but it failed after hours.. Could you help me ?
