### ISSUE TITLE
No camera for some videos

### ISSUE THREAD

**Issue by Aubret** [GAP-LAB-CUHK-SZ/MVImgNet#18]
Hi,

Thank you for your great work ! I downloaded the MVImgNet dataset and I noticed that sometimes there is nothing in the sparse folder. Is it normal ?

**Comment by yshen47** [comment]
I also notice that issue. Besides camera, probably 30% of the scene have missing images

**Comment by hugoycj** [comment]
Sorry for the late reply. Some of the scene reconstructions failed due to issues with the source images for lacking adequate textures. We do not clean them out in our current release version. Please feel free to exclude those unsuccessful reconstructions from the dataset.
