### ISSUE TITLE
(23) Failed writing body

### ISSUE THREAD

**Issue by qqlu** [GAP-LAB-CUHK-SZ/MVImgNet#19]
Hi,

After using the curl command to download the files, I met a new problem indicating "failed writing body" as follows:

![image](https://github.com/GAP-LAB-CUHK-SZ/MVImgNet/assets/7111259/f55cc862-177a-4c02-b62d-820f335025ac)

Could anyone meets this problem?

**Comment by mutianxu** [comment]
You may refer to https://github.com/GAP-LAB-CUHK-SZ/MVImgNet/issues/17.

**Comment by qqlu** [comment]
Thanks.

I find it that it does not affect the unzip process.

Lu
