### ISSUE TITLE
Masks seem not very clear

### ISSUE THREAD

**Issue by ckrsls** [GAP-LAB-CUHK-SZ/MVImgNet#22]
Hi developers,
First of all, thank you for creating such a large-scale dataset.
I am trying to reconstruct point clouds using your multi-view data set with masks, but I find some masks not very clear. Like this:
![005 jpg](https://github.com/GAP-LAB-CUHK-SZ/MVImgNet/assets/99343978/45ee9bea-7630-461d-a24e-9b3f138cc039)
![007 jpg](https://github.com/GAP-LAB-CUHK-SZ/MVImgNet/assets/99343978/e6b08ea9-0e7a-4441-a224-ca9ca9f7543a)
I want to know:
1. How did you create these masks? 
2. How were the clear pointclouds in MVPNet made?
3. Is there anyway to optimize masks？

**Comment by Larry-u** [comment]
1&2: details can be found in the paper. 3: better segmentation methods can be used, e.g. SAM

**Comment by erceguder** [comment]
Hey @ckrsls, thank you for creating a discussion on this. I wonder where the masks are located under the folder structure. Is it under `sparse` folder of each sequence?
