### ISSUE TITLE
Cannot open the download link

### ISSUE THREAD

**Issue by co1dspring** [GAP-LAB-CUHK-SZ/MVImgNet#25]
After I filled the form, the website shows: 此链接已删除。
很抱歉，已删除对此文档的访问权限。请联系与你共享它的人员。

**Comment by QitaoZhao** [comment]
Same issue here!

**Comment by mutianxu** [comment]
Due to the policy update of Microsoft OneDrive, the shared folder exceeds the limited size of the new policy, we are working on it, and will solve it ASAP! Thanks a lot for your issue, and apology for the delay.

**Comment by Binyr** [comment]
mark

**Comment by HeliosZhao** [comment]
> Due to the policy update of Microsoft OneDrive, the shared folder exceeds the limited size of the new policy, we are working on it, and will solve it ASAP! Thanks a lot for your issue, and apology for the delay.

Thanks a lot for your great work! Is it possible to load the dataset on Huggingface? HuggingFace dataset can also require users to sign the term of use and license. In addition, it would be much more convenient to download than OneDrive.

**Comment by KaiWU5** [comment]
thanks for our great work, also hands up agree for uploading to huggingface or google drive

**Comment by mutianxu** [comment]
Dear All,

The valid link has been updated. 

You may submit the request again.

Apologize for the delay.

As for huggingface, we are also working on it. We will announce it when it is ready.

Thanks!
