### ISSUE TITLE
MVPNet download link is down.

### ISSUE THREAD

**Issue by zyc00** [GAP-LAB-CUHK-SZ/MVImgNet#27]
<img width="625" alt="Screenshot 2024-04-11 at 10 29 51 AM" src="https://github.com/GAP-LAB-CUHK-SZ/MVImgNet/assets/61403116/db335662-c8b4-4d68-9e51-ca06f69f667d">

**Comment by mutianxu** [comment]
Thanks for your notice! 

We are fixing on it, and will notify you when it is ready.

**Comment by mutianxu** [comment]
@zyc00 Hi, the download link has been updated. 
Please fill out the form again and get the updated link.

Apologize for the delay.

Thanks!

**Comment by zyc00** [comment]
@mutianxu Thanks for your update!
