### ISSUE TITLE
How to get the segmentation masks?

### ISSUE THREAD

**Issue by dingdingcai** [GAP-LAB-CUHK-SZ/MVImgNet#3]
Hi, 

Thanks for sharing the dataset!

I downloaded a subset of the dataset and was trying to get the dense foreground mask, but I have no clue where and how to get the object mask. Is there any instruction for this? Thanks!

**Comment by Larry-u** [comment]
Hi, thanks for your interest of MVImgNet.

We are preparing the foreground mask and will upload them to Onedrive soon. The masks are generated using CarveKit - an image background removing tool based a U^2 Net.

**Comment by dingdingcai** [comment]
Hi, may I ask when the foreground masks will be available? Is there any specific schedule for this?
