### ISSUE TITLE
Missing class for "MVImgNet_by_categories"

### ISSUE THREAD

**Issue by dongwoohhh** [GAP-LAB-CUHK-SZ/MVImgNet#31]
Thanks for the nice work.

I hope I can use partial classes of your dataset, but it seems that zip files for all classes are not provided under the "MVImgNet_by_categories" folder.

Could you please provide download links for the classes that are not currently uploaded?

**Comment by mutianxu** [comment]
Thanks for your question.

In fact, we provide "MVImgNet_by_categories" just for partial debugging/testing on specific categories, so it is incomplete.

To access all categories, you need to download all the mvi_xxx.zip files directly. 

We have provided the Linux download script in README, so it will be very convenient now.

Hope this is helpful!

**Comment by dongwoohhh** [comment]
I understood your reply!

Thanks for fast response.
