### ISSUE TITLE
Overlap between MVimgNet classes and Imagenet classes

### ISSUE THREAD

**Issue by matheusfreitasmv** [GAP-LAB-CUHK-SZ/MVImgNet#34]
Hi,

I appreciate you providing the dataset. I attempted to identify the common classes between the two datasets using the provided list, but I found fewer than the number mentioned in the description.

"The objects in our MVImgNet are found or used in human daily life (human-centric), where 65 classes overlap with ImageNet."

I couldn't find the 65 classes that overlap with ImageNet. Is it possible to provide these overlapped classes, please?

Thank you.

**Comment by mutianxu** [comment]
Please refer to https://github.com/GAP-LAB-CUHK-SZ/MVImgNet/issues/32. Thanks!
