### ISSUE TITLE
Correspondence between the zip file and object category

### ISSUE THREAD

**Issue by Red-Fairy** [GAP-LAB-CUHK-SZ/MVImgNet#7]
Thanks for the great dataset! However, the dataset is extremely huge, and I'm only interested in some specific categories. Therefore, could you provide the correspondence between the zip file and the object category?

Thanks in advance!

**Comment by Larry-u** [comment]
Hi, thanks for your interest!

We split the data randomly, so there is no such a correspondence.

Could you please tell us which categories are you interested in?  Since we are planning to package the data by categories, we can upload these categories in priority.

**Comment by Red-Fairy** [comment]
Thanks for your quick response! 

I'm interested in those containers. I think they're simple in shape and thus suitable for my project.

**Comment by Larry-u** [comment]
Could you provide us with specific class_labels? So that we can better prepare them.

**Comment by Red-Fairy** [comment]
The class_labels are 0, 1, 14, 26, 39, 43, 48, 49, 83, 119, 160.

Thanks in advance!

**Comment by Marquess98** [comment]
Hi, thanks for the wonderful work! I am also interested the category of pipes whose class_label is 145. Could you please helping me upload it? Thank you!

**Comment by qinxiaodeng** [comment]
> Hi, thanks for your interest!
> 
> We split the data randomly, so there is no such a correspondence.
> 
> Could you please tell us which categories are you interested in? Since we are planning to package the data by categories, we can upload these categories in priority.
Thanks for the wonderful work! I am interested in fruit and vegetable categories.Could you help me get the data in these categories?
Thanks in advance!

**Comment by qinxiaodeng** [comment]
> Could you provide us with specific class_labels? So that we can better prepare them.

Thanks for the wonderful work! I am interested in fruit and vegetable categories.Could you help me get the data in these categories?
Thanks in advance!

**Comment by Larry-u** [comment]
> > Could you provide us with specific class_labels? So that we can better prepare them.
> 
> Thanks for the wonderful work! I am interested in fruit and vegetable categories.Could you help me get the data in these categories? Thanks in advance!

Could you provide the class labels?

**Comment by Larry-u** [comment]
@Red-Fairy @Marquess98 Hi there, your requested categories have been uploaded in priority, you can find them under `MVImgNet_by_categories` now :D

We will leave this issue open until we uploaded all classes.

**Comment by MissingJoe** [comment]
Hi, thanks for the fantastic work for multi-view dataset. I'm working on multi-view classification now, so I'm interested only with the raw image and image label. The full dataset is so huge to download. Could you please release the dataset with raw image and label only later?

**Comment by 20throokie** [comment]
Hi, nice work! I am interested in furniture 3d model reconstruction. Could you please provide class label 6, 8, 29, 46, 79 in a zip file? Thanks.

**Comment by interstellar-ai** [comment]
The class_labels are 36, 45, 46, thanks a lot !!!

**Comment by Larry-u** [comment]
@20throokie @interstellar-ai Done.

**Comment by triton99** [comment]
Hi @Larry-u , Thank you for your great works.
Could you please provide class label [1, 2, 6, 7, 8, 13, 15, 16, 19, 20, 22, 24, 28, 29, 31, 32, 33, 34, 35, 36, 37, 39, 40, 41, 43, 44, 45, 46, 47, 50, 53, 76, 77, 86, 93, 94, 99, 100, 108, 112, 113, 114, 125, 126, 127, 129, 132, 133, 138, 139, 141, 146, 147, 148, 149, 150, 152, 153, 154, 156, 163, 167, 168, 192, 195, 197, 205, 206, 207, 208, 211, 212, 215, 216, 217, 218, 219, 220, 222, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 237, 240, 241, 243, 246, 251, 252, 253, 266, 267] in zip file.

**Comment by triton99** [comment]
Hi @Larry-u, Thank you for your great work.
Could you please provide class label [1, 2, 6, 7, 8, 13, 15, 16, 19, 20, 22, 24, 28, 29, 31, 32, 33, 34, 35, 36, 37, 39, 40, 41, 43, 44, 45, 46, 47, 50, 53, 76, 77, 86, 93, 94, 99, 100, 108, 112, 113, 114, 125, 126, 127, 129, 132, 133, 138, 139, 141, 146, 147, 148, 149, 150, 152, 153, 154, 156, 163, 167, 168, 192, 195, 197, 205, 206, 207, 208, 211, 212, 215, 216, 217, 218, 219, 220, 222, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 237, 240, 241, 243, 246, 251, 252, 253, 266, 267] in zip file?
Thank you a lot.

**Comment by triton99** [comment]
Hi @Larry-u @mutianxu , Thank you for your great work.

Could you please provide class label [1, 2, 6, 7, 8, 13, 15, 16, 19, 20, 22, 24, 28, 29, 31, 32, 33, 34, 35, 36, 37, 39, 40, 41, 43, 44, 45, 46, 47, 50, 53, 76, 77, 86, 93, 94, 99, 100, 108, 112, 113, 114, 125, 126, 127, 129, 132, 133, 138, 139, 141, 146, 147, 148, 149, 150, 152, 153, 154, 156, 163, 167, 168, 192, 195, 197, 205, 206, 207, 208, 211, 212, 215, 216, 217, 218, 219, 220, 222, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 237, 240, 241, 243, 246, 251, 252, 253, 266, 267] in zip file?

Or id inside this categories [mvimagenet.txt](https://github.com/user-attachments/files/16277986/mvimagenet.txt).

Thank you a lot.

**Comment by mutianxu** [comment]
> Hi @Larry-u @mutianxu , Thank you for your great work.
> 
> Could you please provide class label [1, 2, 6, 7, 8, 13, 15, 16, 19, 20, 22, 24, 28, 29, 31, 32, 33, 34, 35, 36, 37, 39, 40, 41, 43, 44, 45, 46, 47, 50, 53, 76, 77, 86, 93, 94, 99, 100, 108, 112, 113, 114, 125, 126, 127, 129, 132, 133, 138, 139, 141, 146, 147, 148, 149, 150, 152, 153, 154, 156, 163, 167, 168, 192, 195, 197, 205, 206, 207, 208, 211, 212, 215, 216, 217, 218, 219, 220, 222, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 237, 240, 241, 243, 246, 251, 252, 253, 266, 267] in zip file?
> 
> Or id inside this categories [mvimagenet.txt](https://github.com/user-attachments/files/16277986/mvimagenet.txt).
> 
> Thank you a lot.

Please see https://github.com/GAP-LAB-CUHK-SZ/MVImgNet/blob/main/mvimgnet_category.txt

**Comment by triton99** [comment]
Hi @mutianxu , @Larry-u.

Could you help me get the data in these categories [1, 2, 6, 7, 8, 13, 15, 16, 19, 20, 22, 24, 28, 29, 31, 32, 33, 34, 35, 36, 37, 39, 40, 41, 43, 44, 45, 46, 47, 50, 53, 76, 77, 86, 93, 94, 99, 100, 108, 112, 113, 114, 125, 126, 127, 129, 132, 133, 138, 139, 141, 146, 147, 148, 149, 150, 152, 153, 154, 156, 163, 167, 168, 192, 195, 197, 205, 206, 207, 208, 211, 212, 215, 216, 217, 218, 219, 220, 222, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 237, 240, 241, 243, 246, 251, 252, 253, 266, 267] in zip file like in `MVImgNet_by_categories` folder for download? The mvi_xx.zip split the data randomly.

Thank you very much.
