### ISSUE TITLE
MVPNet for point cloud classification

### ISSUE THREAD

**Issue by LiJin73** [GAP-LAB-CUHK-SZ/MVImgNet#8]
Thank you for your excellent work. Could you please provide the specific file partition and corresponding labels of the training and test of the MVPNet dataset for point cloud classification challenge in the paper? By the way, I noticed in section 6.1 of the paper that MVPNet has 150 classes, however, there are 180 classes in the provided files. Thank you very much.

**Comment by sz3623** [comment]
Thank you for your excellent work. Could you please provide the correspondence between file number and category name? For classification tasks, is the training process performed with random sampling of 1024 or 2048 points?  Would you mind giving a detailed description of the experiment？Thanks a lot!

**Comment by UncleMEDM** [comment]
@LiJin73 Hi, we further clean more point clouds, and add some new point clouds after the paper released, therefore there are 180 categories finally.

**Comment by UncleMEDM** [comment]
@sz3623 Hi, the files are already categorized into different folder, and the folder name is the category id. You should be able to find the catgeory name in /mvimgnet_category.txt. During the training in point cloud classification, we randomly sample 2048 points from each point cloud, and normalize the point cloud by the following code snippet:
xyz = point_cloud[:, 0:3]
xyz_center = np.mean(xyz, axis=0)
xyz = xyz - xyz_center
point_dist = np.sqrt(np.sum(xyz ** 2, axis=1))
median_dist = np.median(point_dist)
xyz = xyz / median_dist
Moreover, data augmentation is added such as random rotation in all three axis between -45 degree to 45 degree.

**Comment by LiJin73** [comment]
> @LiJin73 Hi, we further clean more point clouds, and add some new point clouds after the paper released, therefore there are 180 categories finally.

Thanks for your reply. In fact, I want to follow the MVPNet Benchmark in the paper, so could you please provide the specific file partition of the 64000 training samples and 16000 testing samples mentioned in the paper? Thanks a lot.

**Comment by UncleMEDM** [comment]
@LiJin73 Hi, since the MVPNet is slightly different than the previous version, so I may need to re-split the data and train on them again. I will release the new train/val split ASAP. And quantitative experiments on previous point cloud classification method on MVPNet will be updated soon.

**Comment by LiJin73** [comment]
@UncleMEDM Okay, I understand. Looking forward to the updated partition file and experiment results. Thank you again.

**Comment by UncleMEDM** [comment]
> @UncleMEDM Okay, I understand. Looking forward to the updated partition file and experiment results. Thank you again.

Hi, the train/val split is already released.
